### ISSUE TITLE
In SQL statements, Values are inserted as parameters with placeholders

### ISSUE THREAD

**Issue by DrDiHai** [SwissGacho/Haushaltbuch#50]

**Comment by hk-ret** [comment]
@DrDiHai, übrigens: die Parameter müssen nur innerhalb eines SQL-Befehls eindeutig sein. Der Zähler sollte deshalb in der 'Top-Parent' Instanz geführt werden. Sonst gibt es schon spätestens beim zweite Ausführen des selben Befehls eine Kollision. Man könnte dann auch statt eine Liste (Set) von Namen zu führen vom 'Top-Parent' aus den 'SQL-Baum' durchsuchen.

**Comment by hk-ret** [comment]
@DrDiHai, noch was: die Parameter Namen dürfen nicht reine Zahlen sein. Ich schlage vor einfach den Default-Namen für Value's "param" oder "value" zu nennen (statt None). Dann wird der Name automatisch mit dem Zähler dedupliziert.
